---
server:
  port: 8761
spring:
  profiles: registerA
  application:
    name: eureka-server-A
eureka:
  instance:
    hostname: register1
  client:
    serviceUrl:
      defaultZone: http://register2:8762/eureka/
 
---
server:
  port: 8762
spring:
  profiles: registerB
  application:
    name: eureka-server-B
eureka:
  instance:
    hostname: register2
  client:
    serviceUrl:
      defaultZone: http://register1:8761/eureka/
